[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/pedvide/ADC
  https://github.com/FrankBoesing/FastCRC

[env:teensy41_bench]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
upload_protocol = teensy-cli
build_flags =
  -DPQ_BENCH_MODE=1
lib_deps =
  https://github.com/pedvide/ADC
  https://github.com/FrankBoesing/FastCRC
